### ISSUE TITLE
Cours problem 

### ISSUE THREAD

**Issue by guybarner** [Goldenfreddy0703/Otaku#246]
It looks like when you want to see anime with a second cour, and you see the second cour the search is for the first episode of the season and not the cour. For example when you see mushoku tensei 2 season 2 cour first episode, it look like it searches for 2×1 which is the first episode of the season and not the cour

**Comment by guybarner** [comment]
Also spacial episode like episode 0 you can't find any sources at all

**Comment by Goldenfreddy0703** [comment]
Yeah, course have always been a problem unfortunately especially with torrents due to how we scrap torrents, for embeds tho, it shouldn't be a problem unless Anilist Database has something to do with it. Hopefully embeds should help you out tho.

**Comment by guybarner** [comment]
Is there any chance that in the future you guys will fix this. By the way wanted to say that other than that you did really great addon :)

**Comment by Goldenfreddy0703** [comment]
Unfortunately I don't think so but I may have an idea on what I could do.

**Comment by guybarner** [comment]
Oh well, thanks any way

**Comment by Goldenfreddy0703** [comment]
Hey so good news, I came up with an idea on how we can make torrent scrapping very consistent, hopefully tomorrow it will be complete. I already worked on the first part of it where seasons and parts will be stored in a database, now we just need to pass those to the torrent scrapper and we should be good.

**Comment by guybarner** [comment]
Amazing work! Thank you very much 😄

**Comment by theasguard** [comment]
this will be great, i recently searched a fate series (fate/Apocrypha) and the only result it returned was an erai-raws result, even though there was multiple duel audios and subs, hopefully these improvements to torrents will help with that..
sorry for coming in here like i owned the place, figured since it was a torrents thing my problem might fit into it also haha.

**Comment by Goldenfreddy0703** [comment]
Heyyyy so great news, Sense im a still a bit clueless on scrapping, i have made a setting called "Scrape Torrents Consistently" where scrapping will be consistent when scrapping torrents. Hopefully this will resolve your issue and hopefully this will improve finding the right sources for that particular anime. A release should be out so please test it and tell us what you think. 

We are gonna go ahead and close this issue but if you have any questions or concerns or issues related to this, feel free to reply in here and we will open this back up.
Thank you

**Comment by Goldenfreddy0703** [comment]
> this will be great, i recently searched a fate series (fate/Apocrypha) and the only result it returned was an erai-raws result, even though there was multiple duel audios and subs, hopefully these improvements to torrents will help with that.. sorry for coming in here like i owned the place, figured since it was a torrents thing my problem might fit into it also haha.

heyyyyy so we just released an update and i forgot to test fate/Apocrypha. turns out it confused itself with alot of different animes so you may wanna use embeds on this while we try to fix that soon. Its cause of the "/", idk why its weird

**Comment by guybarner** [comment]
Hi, it seems the the fix to the problem with cours worked, but It seems that you can't scarp animetosho and the scarp consistently throws an error, it seems like you do SQL query for  the column thetvdb_part which doesn't exist

**Comment by guybarner** [comment]
And special episode still doesn't work, it throws an error "type error: 'NOneType' object is not subscritable". It happens in line 4678 in _get_titles

**Comment by Goldenfreddy0703** [comment]
> Hi, it seems the the fix to the problem with cours worked, but It seems that you can't scarp animetosho and the scarp consistently throws an error, it seems like you do SQL query for the column thetvdb_part which doesn't exist

Hey there, there is a dependency called script.otaku.mappings, see if you have the latest version of that and that may fix your issues.

**Comment by Goldenfreddy0703** [comment]
> And special episode still doesn't work, it throws an error "type error: 'NOneType' object is not subscritable". It happens in line 4678 in _get_titles

special episodes most likely have problems with playing, if you could tell me the show and episode so i can reproduce, that would be great. Thanks

**Comment by guybarner** [comment]
I think I know what the problem with this special episode, https://myanimelist.net/anime/55818/Mushoku_Tensei_II__Isekai_Ittara_Honki_Dasu_-_Shugo_Jutsushi_Fitz
I see now that anilist doesn't have this as a separate entry, so trying to scarp from the mal entry that what does the problem. 
For the second one I'll check and let you know.
And again thanks so much about the amazing work

**Comment by guybarner** [comment]
> > Hi, it seems the the fix to the problem with cours worked, but It seems that you can't scarp animetosho and the scarp consistently throws an error, it seems like you do SQL query for the column thetvdb_part which doesn't exist
> 
> Hey there, there is a dependency called script.otaku.mappings, see if you have the latest version of that and that may fix your issues.
> 
> Latest Version should be 24.04.27

Seems like now it works. Thanks very much 😁
