### ISSUE TITLE
Nvidia Shield and Firestick Issues

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Goldenfreddy0703/Otaku#69]
## Important Information:
If you guys are experiencing bugs such as Scrapping, Play Next, Pls provide this issue below, a log, and maybe some screenshots as well and we will look into it more. 

## Note: 
Make sure to try all my troubleshooting steps including Wiping Addon Data before posting. 

Thank you

## Solutions:
1. Try disabling IPv6.
2. Update Kodi to the nightly version.
3. Make sure your updated to the latest version.

**Comment by Calavera999** [comment]
Although I'm on Xbox, I was told by Goldenfreddy0703 to comment here.

I am on Xbox and latest version of Otaku has suddenly stopped scraping Nyaa for torrents and my Debrid username shows as blank in Otaku settings, which it wasn't doing previously. This was all working fine until I did a reinstall of Otaku.

I get plenty of embeds, but never any torrents.

When I authenticate my Real Debrid account Otaku tells me all is successful and the device gets listed in my Real Debrid account, so all seems to be correct - except the username field in Otaku settings remains blank.

**Comment by ShibajiCh** [comment]
My issue with Otaku in Nvidia Shield TV Pro is mentioned in ticket #67. Just wanted to add it here to keep it in loop with the ongoing issues that are happening with Shield and Nexus as suggested by @Goldenfreddy0703 above.

**Comment by Goldenfreddy0703** [comment]
> My issue with Otaku in Nvidia Shield TV Pro is mentioned in ticket #67. Just wanted to add it here to keep it in loop with the ongoing issues that are happening with Shield and Nexus as suggested by @Goldenfreddy0703 above.

Right, one question, have you tried disabling ipv6 on your nvidia shield?

**Comment by ShibajiCh** [comment]
> > My issue with Otaku in Nvidia Shield TV Pro is mentioned in ticket #67. Just wanted to add it here to keep it in loop with the ongoing issues that are happening with Shield and Nexus as suggested by @Goldenfreddy0703 above.
> 
> Right, one question, have you tried disabling ipv6 on your nvidia shield?

Hi @Goldenfreddy0703,

Yes, IPv6 is already disabled on my Nvidia Shield TV Pro.

Thanks and Regards,
ShibajiCh.

**Comment by anru82** [comment]
I'm having a really weird issue with otaku, while I'm watching an episode it goes automatically to the next one.

**Comment by Goldenfreddy0703** [comment]
Weird, did you try my troubleshooting steps already?

**Comment by anru82** [comment]
Yes I disabled IPv6, installed the last nightly. I even try to clear the cache and rebuild database but nothing works.

**Comment by Goldenfreddy0703** [comment]
Ahhh its possible its do to that NordVPN. If you can't access Nyaa, there is always Nyaa Alt in the addon setting you can enabled and i think that should work for you.

**Comment by dootsie5times** [comment]
I'm not sure if this is the right place for this, but it is an up next issue.
When watching titles that are 10-12 minutes long, like Ao-chan Can't Study, the up next feature does not work.

I'm going to ask something else here.  Is there any chance of putting the "search" option as the last option in the list instead of the next to last?  Gogo addon does this and it makes navigation MUCH easier.

Thanks.

**Comment by dootsie5times** [comment]
I just did a search through the addon for the title.
Version 19.


> What version of Kodi are you running which watchlist are you using?

**Comment by Goldenfreddy0703** [comment]
Interesting, we will take a look at that soon.

**Comment by dootsie5times** [comment]
19.4
> Interesting, we will take a look at that soon. Is it 19.4 of 19.5?

**Comment by dootsie5times** [comment]
I thought of one more thing I periodically experience.....
I THINK it's when Otaku plays a file from Gogo from a server that is not close to me and therefore has a very bad/slow connection.  Sometimes it tries to play the file for like 1-2 seconds (I don't see the file actually play, black screen) and then runs the play next function and other times it starts playing the file, and then either I try to skip ahead or I choose the option to skip the intro and then it runs play next.
I think this could be remedied by having an option/setting to rank the Gogo servers in best to worst order.  I know this is an issue from having used the Gogo addon and experiencing lag from specific servers.  From that experience, I know which ones to pick and which ones to avoid.
I never have this issue with Zoro.
I'm wondering if it might be helpful to have a "debug" option in the addon that you could toggle on to have it it display something like, "playing (anime title name) from (service [gogo/zoro/etc]) from (server_name)" for 5 or so seconds before it start to try to play the file.  This would allow any user of any experience level to provide you with feedback information for troubleshooting.

**Comment by dootsie5times** [comment]
I just tried the new "filter subs and dubs" option and set it to Dub and pretty much all the lists are blank.
I thought, although I may be wrong, that doing this would list only titles that have dub versions available.
Is this how it is supposed to work, or am I totally off base here?

**Comment by Goldenfreddy0703** [comment]
Do all the troubleshooting steps. If that doesn't work, it's possible that you may need to Wipe Addon Data.

**Comment by dootsie5times** [comment]
Do you have a list of these steps?

**Comment by Goldenfreddy0703** [comment]
Oh yeah, I thought people would already know about that in the pinned issues. 

https://github.com/Goldenfreddy0703/Otaku/issues/15

**Comment by dootsie5times** [comment]
What does the "wipe addon data" do....just delete settings or something?

**Comment by Goldenfreddy0703** [comment]
Yes, wipe addon setting completely wipes your appdata and a mal dubs file is stored on there which could probably be the reason why your dubs are blank.

**Comment by Goldenfreddy0703** [comment]
Try clear cache and rebuild database real quick and see if dubs show up, if not then wipe addon data.

**Comment by dootsie5times** [comment]
If clear and rebuild don't work, can I just delete the mal_dub.json file instead of wiping all the addon data?

**Comment by Goldenfreddy0703** [comment]
U can delete the mal_dub.json file instead

**Comment by dootsie5times** [comment]
I tried clearing and rebuilding.  No joy.
Deleted the mal_dub.json file......It now works.
Thanks.

**Comment by Goldenfreddy0703** [comment]
Ayyy your, welcome. In the future I will add a way where anytime you clear cache or rebuild database, it will delete the mal dubs automatically.

**Comment by Goldenfreddy0703** [comment]
> I tried clearing and rebuilding. No joy. Deleted the mal_dub.json file......It now works. Thanks.

Hey so if this ever happens again, rebuild database next time and that should fix it cause i made a release today fixing a few bugs.

**Comment by AakashC2020** [comment]
Hi @Goldenfreddy0703,

When using the new subs and dubs filter, both the versions are still showing dubs like earlier. Is this issue not fixed yet? I guess one should be dubs and another should be subs. Even though I don't use this filter I just thought of notifying you in case if others are facing the same issue.

**Comment by Goldenfreddy0703** [comment]
If your talking about the filter, both where it's showing both titles as dub, that's a skin issue I'm Artic Horizon.

**Comment by AakashC2020** [comment]
> If your talking about the filter, both where it's showing both titles as dub, that's a skin issue im Artic Horizon 2.
> 
> It is working tho.

Hi @Goldenfreddy0703,

Oh okay, so will there be a fix for this in future? Are you going to raise this issue with jurialmunkey by any chance? Just asking because it looks confusing. 🙂

**Comment by Goldenfreddy0703** [comment]
Maybe tomorrow I will, idk it's not really a problem tbh. Tomorrow I will look at other skins I guess and see if the titles are both showing dub.

**Comment by AakashC2020** [comment]
> Maybe tomorrow I will, idk it's not really a problem tbh. Tomorrow I will look at other skins I guess and see if the titles are both showing dub.

Fine @Goldenfreddy0703. No problem. Just thought of informing you. Thanks!

**Comment by joezito129** [comment]
It does not look like a problem with the skin. I think i found a fix for it though.

**Comment by AakashC2020** [comment]
> It does not look like a problem with the skin. I think i found a fix for it though.

Hi @joezito129,

Okay, that sounds great! I shall wait for your update on this issue.

**Comment by Goldenfreddy0703** [comment]
Hey there, a fix should be released in the next few min. Big thanks to @joezito129 for figuring this out.

**Comment by AakashC2020** [comment]
> Hey there, a fix should be released in the next few min. Big thanks to @joezito129 for figuring this out.

Hi @joezito129 and @Goldenfreddy0703,

Thank you both for the fix! The sub and dub texts with the filter looks fine now. 🙂👍🏻

**Comment by dootsie5times** [comment]
I had 3 or so movies bookmarked from about 3 versions back of the Otaku addon.
I just tried playing all 3 from the favorites list and get an error for each.
I'm attaching the section of the log file pertaining to one play attempt.

[log.txt](https://github.com/Goldenfreddy0703/Otaku/files/10770009/log.txt)

If I search for the movie through the addon and play it from there it plays fine.

**Comment by Goldenfreddy0703** [comment]
mmmm not sure what is causing this error, mind telling me the version, movies, and a full log.

**Comment by dootsie5times** [comment]
19.4
Altered Carbon, Harlock, Human Lost

[kodi.log](https://github.com/Goldenfreddy0703/Otaku/files/10770590/kodi.log)

**Comment by Goldenfreddy0703** [comment]
Hey @dootsie5times , sorry i never got back to you but i have looked at your log and it turns out you have a vpn which can cause problems with Otaku. You by anychance not using NordVPN, are you?

**Comment by dootsie5times** [comment]
Yes, but I never had an issue with Otaku at all like this.  It happened regardless of whether the vpn was on or off.
I had updated Otaku with the latest fix and then it started happening.
Weirdly, after rebooting the box, that particular error rectumfied itself.

However, I'm still having a particular issue, "playback failed"
Altered Carbon (dub) - it tries to play it from Gogo from xcdnstream server.  Interestingly, the file does not exist on that server.  I checked using the Gogo addon.  It plays from doodstream,  but not from xcdnstream, even though it does list xcdn as a choice in the gogo addon.  There may be nothing you can do about this issue.

I've experienced this "playback failed" issue before, but couldn't really tell which service/server it was trying to play from for those files at that time.  I will try to pay more attention from now on.
This is the reason I asked if you could add a debug feature where it would display all that info directly in the addon to make testing and diagnosing issues like this much easier from my end.  Many times the screens fly by so fast that I can't read them in time and I don't like digging through the log file.

**Comment by dootsie5times** [comment]
What is the reason you say Otaku has issues with NordVPN but not with other vpns?
Why is nord different?

**Comment by Goldenfreddy0703** [comment]
> What is the reason you say Otaku has issues with NordVPN but not with other vpns?
> Why is nord different?
> 

https://twitter.com/RealDebrid/status/1622587338340589568?s=20

**Comment by Goldenfreddy0703** [comment]
If it helps, try disabling your vpn but enable Nyaa Alt in the providers category in Otaku addons settings then try scrapping something.

**Comment by dootsie5times** [comment]
I'm running CoreElec which is linux and uses OpenVPN so there's no issue like that for me.

If I run into any other issues I will try that as a test.

**Comment by travoncleveland** [comment]
Hi Golden! I'm having a similar issue. I'm on an Nvidia Shield on the latest version of Kodi 19.5. Whenever I'm watching an episode it either randomly goes automatically to the next one or if it's on the newest episode it just stops. I've tried turning off IPV6, turning off NordVPN, toggling the setting to OpenVPN to both TCP and UDP, clearing the cache, rebuilding the database, and still having issues.

**Comment by Goldenfreddy0703** [comment]
Sorry to hear that, im not sure whats going on but it could be real debrid itself due to the nordvpn, at this point, you may want to consider upgrading your kodi, doing a fresh install maybe, trying on a different device maybe but idk, these issues started happening a few weeks ago and all.

**Comment by trey02183** [comment]
I think it was just me being on 19.5. I updated to Kodi 20 then reinstalled everything and I've had no issues for an entire day

**Comment by Goldenfreddy0703** [comment]
Nice glad to hear that, sorry things didn't work out in 19.5, could have been glitches here and there.

**Comment by dootsie5times** [comment]
I just updated to the latest version of Otaku.  I'm not sure if this issue is with this version only or was present on previous version.
I have all possible setting for it set to dub only.
When I go into "movies" under completed last year, it lists movies which are sub only along with movies which are dub.  Of course there is no way to tell until you actually try to play them and there is no stream.  The Quintessential Quintuplets and Teasing Master Takagi-san are examples.

**Comment by Goldenfreddy0703** [comment]
Hey so recently, i just made some setting improvements so that its easier for the user, you may wanna reconfigure a few settings and also you may wanna Clear Cache, Clear Torrent Cache, and Rebuild database, 

Troubleshooting steps will be updated tomorrow.

**Comment by dootsie5times** [comment]
That option is set already.  Did both clears and did rebuild.  Same problem.

**Comment by Goldenfreddy0703** [comment]
Mmm....could be that dub version of movies have not released yet cause dub releases end up later then sub releases.

**Comment by dootsie5times** [comment]
But If hey have not been released, why are they even showing up on a dub movie list?

**Comment by dootsie5times** [comment]
If you go into "Movies" and then go into Genres and pick something like "zombie", it lists movies AND multi episode tv animes.
If you go into something like most voted overall or something, it does list only movies.

**Comment by Goldenfreddy0703** [comment]
> But If hey have not been released/created, why are they even showing up on a dub movie list?
> 

Cause the dubs are coming from Mal list and we don't know how we can get airing dates for dubs.

For Genres, I was too lazy to mess with them cause i would have to make separate Genres for movies and tv shows. It's also the same as search.

**Comment by Goldenfreddy0703** [comment]
Hey everyone in this issue post, i think its time to close these issue cause most of these issues that you guys had should mostly be fixed due to our updates. 

- Verizon users should be able to use Firestick and Nvidia Shield by enabling nyaa alt (nyaa alt was fixed previously)
- Real Debrid and NordVPN should be fixed hopefully.
- Make sure ip6 is disabled.
- Reset your router if necessary .
- Reauthenticate your debrid if you don't see your token in the settings.xml file. 
- Dub and Sub should be fixed as well as scrapping from nyaa.
- Make sure to be on kodi 20 or above in order to not have most of these issues.
- If nothing works, reinstall the addon and dependency if necessary and clear all addon data when uninstalling.

If you guys have any question or want to keep this issue post open, feel free to contact me and hope these steps help.

**Comment by Goldenfreddy0703** [comment]
> If you go into "Movies" and then go into Genres and pick something like "zombie", it lists movies AND multi episode tv animes.
> If you go into something like most voted overall or something, it does list only movies.

Hey so I thought about what you said about going into movies then going to genres, ect and I made a big release today on alot of menu changes and worked on search and genres for both movies and tv shows so hopefully thay will help your issue. This time I wasn't lazy like last time to work on those sense I had the knowledge for it. Hope this helps and if you have any more questions, feel free to contact me and reply here if you like.
